name: Build
on: push
jobs:
  build:
    name: Test compiling 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v1.0.0
      with:
        platform-default-url: https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json